services:
  _defaults:
    public: true
  
  prestashop.module.combinationeditor.data_provider.attribute_data_provider:
    class: 'PrestaShop\Module\CombinationEditor\DataProvider\AttributeDataProvider'
  
  prestashop.module.combinationeditor.data_provider.attribute_group_data_provider:
    class: 'PrestaShop\Module\CombinationEditor\DataProvider\AttributeGroupDataProvider'

  prestashop.module.combinationeditor.choice_provider.attribute_group_choice_provider:
    class: 'PrestaShop\Module\CombinationEditor\ChoiceProvider\AttributeGroupChoiceProvider'
    arguments:
      - '@prestashop.module.combinationeditor.data_provider.attribute_group_data_provider'
      - '@=service("prestashop.adapter.legacy.context").getLanguage().id'

  prestashop.module.combinationeditor.command_handler.set_combination_attributes_command_handler:
    class: 'PrestaShop\Module\CombinationEditor\CommandHandler\SetCombinationAttributesCommandHandler'
    tags:
      - name: tactician.handler
        command: 'PrestaShop\Module\CombinationEditor\Command\SetCombinationAttributesCommand'

  prestashop.module.combinationeditor.query_handler.get_combination_attributes_handler:
    class: 'PrestaShop\Module\CombinationEditor\CommandHandler\GetCombinationAttributesHandler'
    tags:
      - name: tactician.handler
        command: 'PrestaShop\Module\CombinationEditor\Query\GetCombinationAttributes'

  prestashop.module.combinationeditor.form.data_provider.combination_attributes_data_provider:
    class: 'PrestaShop\Module\CombinationEditor\Form\DataProvider\CombinationAttributesDataProvider'
    arguments:
      - '@prestashop.core.query_bus'

  prestashop.module.combinationeditor.form.combination_attribute_item_type:
    class: 'PrestaShop\Module\CombinationEditor\Form\CombinationAttributeItemType'
    arguments:
      - '@prestashop.module.combinationeditor.choice_provider.attribute_group_choice_provider'
      - '@prestashop.module.combinationeditor.data_provider.attribute_data_provider'
      - '@=service("prestashop.adapter.legacy.context").getLanguage().id'
    tags:
      - { name: form.type }

  prestashop.module.combinationeditor.form.identifiable_object.builder.combination_attributes_form_builder:
    class: 'PrestaShop\PrestaShop\Core\Form\IdentifiableObject\Builder\FormBuilder'
    factory: 'prestashop.core.form.builder.form_builder_factory:create'
    arguments:
      - 'PrestaShop\Module\CombinationEditor\Form\CombinationAttributesType'
      - '@prestashop.module.combinationeditor.form.data_provider.combination_attributes_data_provider'
